#!/bin/bash

echo ""
echo "🌐 ngrok Tunnel URL:"
echo "======================================"
curl -s http://localhost:4040/api/tunnels | grep -o '"public_url":"https://[^"]*' | grep -o 'https://.*' | head -1
echo "======================================"
echo ""
echo "�️  ngrok Web UI: http://localhost:4040"
echo ""
echo "�📋 Use the tunnel URL as the base for your TradingView webhooks"
echo ""
echo "Example webhook URLs:"
echo ""
echo "📋 Webhook Endpoints for TradingView:"
echo "  • RSI Crossed Up:  [TUNNEL_URL]/webhook/rsi/crossed-up"
echo "  • RSI Crossed Down:[TUNNEL_URL]/webhook/rsi/crossed-down"
echo "  • RSI Moving Down: [TUNNEL_URL]/webhook/rsi-moving-down"
echo "  • RSI Moving Up:   [TUNNEL_URL]/webhook/rsi-moving-up"
echo "  • MACD Cross Up:   [TUNNEL_URL]/webhook/macd-cross-up"
echo "  • MACD Cross Down: [TUNNEL_URL]/webhook/macd-cross-down"
echo "  • MACD Moving Up:  [TUNNEL_URL]/webhook/macd-moving-up"
echo "  • MACD Moving Down:[TUNNEL_URL]/webhook/macd-moving-down"
echo ""
echo "💡 Visit http://localhost:4040 to see incoming webhook requests in real-time!"
echo ""
